# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('source_ip', models.CharField(max_length=64)),
                ('source_port', models.IntegerField()),
                ('destination_ip', models.CharField(max_length=64)),
                ('destination_port', models.IntegerField()),
                ('sensor', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('password1', models.CharField(max_length=128)),
                ('password2', models.CharField(max_length=128)),
                ('password3', models.CharField(max_length=128)),
                ('username1', models.CharField(max_length=128)),
                ('username2', models.CharField(max_length=128)),
                ('username3', models.CharField(max_length=128)),
                ('macCS', models.CharField(max_length=1024)),
                ('kexAlgs', models.CharField(max_length=1024)),
                ('keyAlgs', models.CharField(max_length=1024)),
                ('encCS', models.CharField(max_length=1024)),
            ],
        ),
    ]
