# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowrie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshsession',
            name='version',
            field=models.CharField(default=2, max_length=1024),
            preserve_default=False,
        ),
    ]
